//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiteGenerator
{
    using System;
    using System.Collections.Generic;
    
    public partial class CSS_GEN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CSS_GEN()
        {
            this.CSS_HTML = new HashSet<CSS_HTML>();
        }
    
        public string PROPERTY_NAME { get; set; }
        public int TYPE_ROW { get; set; }
        public string DISCRIPTION_CSS { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CSS_HTML> CSS_HTML { get; set; }
    }
}
