//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiteGenerator
{
    using System;
    using System.Collections.Generic;
    
    public partial class HTML_GEN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HTML_GEN()
        {
            this.CSS_HTML = new HashSet<CSS_HTML>();
            this.HTML_ATTR = new HashSet<HTML_ATTR>();
        }
    
        public string TAG { get; set; }
        public string POSITION { get; set; }
        public string DISCRIPTION_TAG { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CSS_HTML> CSS_HTML { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HTML_ATTR> HTML_ATTR { get; set; }
    }
}
