//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiteGenerator
{
    using System;
    using System.Collections.Generic;
    
    public partial class HTML_ATTR
    {
        public int ID { get; set; }
        public string TAG { get; set; }
        public string NAME_ATTR { get; set; }
    
        public virtual HTML_GEN HTML_GEN { get; set; }
    }
}
