//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiteGenerator
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SiteGeneratorContext : DbContext
    {
        public SiteGeneratorContext()
            : base("name=SiteGeneratorContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CSS_GEN> CSS_GEN { get; set; }
        public virtual DbSet<CSS_HTML> CSS_HTML { get; set; }
        public virtual DbSet<HTML_ATTR> HTML_ATTR { get; set; }
        public virtual DbSet<HTML_GEN> HTML_GEN { get; set; }
    }
}
